### ISSUE TITLE
Is this the same version as in the blogpost?

### ISSUE THREAD

**Issue by ghost** [arnaucube/blogo#3]
Hi,

I'm trying to code through your blog post here:

[https://arnaucube.com/blog/](https://arnaucube.com/blog/)

I'm getting a lot of errors and can't import strings in files.go 

I'm using blogo as a base an make my own version to learn more about building static site generators with Go.

If you made any changes to the code which aren't in the blog post or you have any other hints that would be very helpful.

**Comment by arnaucube** [comment]
Hi @nfuhs ,
Yes, the blog post was from a earlier version.

I've uploaded a small repo with the example use of blogo at the current version: https://github.com/arnaucube/blogoExample

**Comment by ghost** [comment]
Thanks for the help @arnaucube ! Will take a look at this version if I have more questions I will just let you know.
